service: lambda-dynamodb-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:ListTables
      Resource: "arn:aws:dynamodb:sa-east-1:258835071595:table/*"

functions:
  createTodo:
    handler: src/api/features/features.handler.run
    events:
      - http:
          path: features
          method: post
  listTables:
    handler: list.run
    events:
      - http:
          path: todos
          method: get
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: todos
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
