service: lambda-dynamodb-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:ListTables
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:sa-east-1:258835071595:table/*"

functions:
  createFeature:
    handler: dist/index.createFeatureHandler
    events:
      - http:
          path: /features
          method: post

  listFeature:
    handler: dist/index.listAllFeaturesHandler
    events:
      - http:
          path: /features
          method: get

  getFeature:
    handler: dist/index.getFeatureHandler
    events:
      - http:
          path: /features/{id}
          method: get

  deleteFeature:
    handler: dist/index.deleteFeatureHandler
    events:
      - http:
          path: /features/{id}
          method: delete

  updateFeature:
    handler: dist/index.updateFeatureHandle
    events:
      - http:
          path: /features/{id}
          method: put

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: todos
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
